on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - uses: actions/setup-node@v2
        with:
          node-version: v16.14.0
          cache: 'pnpm'

      - name: validate all params.json
        run: ajv -s params.schema.json -d "queries/*/params.json"

      - name: build
        run: pnpm run build
